import type { CrawlUrlRow } from '@freecrawl/shared-types';
import type { TabKey } from '../store.js';

export interface ColumnSpec {
  /**
   * Unique UI id for this column (React key, width storage, resize). Defaults
   * to `key`, but two specs can share the same data `key` — e.g. Indexability
   * and Indexability Status both read `indexability` but must render as
   * separate columns with their own widths.
   */
  id?: string;
  key: keyof CrawlUrlRow;
  header: string;
  size: number;
  align?: 'left' | 'right';
  kind?: 'status' | 'mono' | 'number' | 'indexability' | 'indexability-status' | 'text';
  /** Tooltip description shown next to the header (info icon). */
  info?: string;
  /** Concrete example/value rendered under "Example" in the header tooltip. */
  example?: string;
}

export function columnId(c: ColumnSpec): string {
  return c.id ?? (c.key as string);
}

const COL = {
  url: {
    key: 'url',
    header: 'URL',
    size: 460,
    kind: 'mono',
    info: 'The fully normalised URL of the crawled resource (post URL-rewriting).',
    example: 'https://example.com/blog/post-1',
  } as ColumnSpec,
  status: {
    key: 'statusCode',
    header: 'Status',
    size: 72,
    kind: 'status',
    info: 'HTTP response status code. Empty/Failed indicates a network error before any response was received.',
    example: '200, 301, 404, 500',
  } as ColumnSpec,
  contentKind: {
    key: 'contentKind',
    header: 'Type',
    size: 72,
    kind: 'text',
    info: 'Coarse content classification derived from URL extension and Content-Type header.',
    example: 'html, js, css, image, pdf, font, other',
  } as ColumnSpec,
  indexability: {
    key: 'indexability',
    header: 'Indexability',
    size: 130,
    kind: 'indexability',
    info: 'Whether the URL is eligible to appear in search results. Combines status code, robots directives, canonical, and meta-refresh signals.',
    example: 'Indexable / Non-Indexable',
  } as ColumnSpec,
  indexabilityStatus: {
    id: 'indexability-status',
    key: 'indexability',
    header: 'Indexability Status',
    size: 200,
    kind: 'indexability-status',
    info: 'Specific reason a URL is non-indexable. For Indexable URLs this column is empty.',
    example: 'noindex, canonicalised, redirected, blocked-by-robots',
  } as ColumnSpec,
  title: {
    key: 'title',
    header: 'Title 1',
    size: 320,
    kind: 'text',
    info: 'Contents of the first <title> element. Google primarily uses this in SERP titles.',
    example: 'Buy Affordable Game Keys | Example Store',
  } as ColumnSpec,
  titleLength: {
    key: 'titleLength',
    header: 'Title 1 Length',
    size: 96,
    kind: 'number',
    info: 'Character count of the title. Recommended: 30–60 characters; over 60 risks truncation in SERPs.',
    example: '52',
  } as ColumnSpec,
  metaDescription: {
    key: 'metaDescription',
    header: 'Meta Description 1',
    size: 340,
    kind: 'text',
    info: 'Contents of the first <meta name="description"> tag. May be used as the SERP snippet.',
    example: 'Shop the latest game keys at unbeatable prices…',
  } as ColumnSpec,
  metaDescriptionLength: {
    key: 'metaDescriptionLength',
    header: 'Meta Description 1 Length',
    size: 140,
    kind: 'number',
    info: 'Character count of the meta description. Recommended: 70–155 characters; over 155 risks truncation.',
    example: '142',
  } as ColumnSpec,
  h1: {
    key: 'h1',
    header: 'H1-1',
    size: 260,
    kind: 'text',
    info: 'Text of the first <h1> on the page. Should match user intent and ideally complement (not duplicate) the title.',
    example: 'Welcome to Example Store',
  } as ColumnSpec,
  h1Length: {
    key: 'h1Length',
    header: 'H1-1 Length',
    size: 96,
    kind: 'number',
    info: 'Character count of the first H1.',
    example: '24',
  } as ColumnSpec,
  h1Count: {
    key: 'h1Count',
    header: 'H1 Count',
    size: 80,
    kind: 'number',
    info: 'Total number of <h1> elements on the page. SEO best practice is exactly 1.',
    example: '1',
  } as ColumnSpec,
  h2Count: {
    key: 'h2Count',
    header: 'H2 Count',
    size: 80,
    kind: 'number',
    info: 'Total number of <h2> elements on the page.',
    example: '4',
  } as ColumnSpec,
  wordCount: {
    key: 'wordCount',
    header: 'Word Count',
    size: 96,
    kind: 'number',
    info: 'Visible body text word count (excludes <script>/<style>). Useful for identifying thin content.',
    example: '650',
  } as ColumnSpec,
  canonical: {
    key: 'canonical',
    header: 'Canonical Link Element 1',
    size: 360,
    kind: 'mono',
    info: 'URL declared by the first <link rel="canonical"> tag. Tells search engines which version to index when duplicates exist.',
    example: 'https://example.com/canonical-version',
  } as ColumnSpec,
  metaRobots: {
    key: 'metaRobots',
    header: 'Meta Robots 1',
    size: 180,
    kind: 'text',
    info: 'Contents of the first <meta name="robots"> tag. Controls per-page indexing/following behaviour.',
    example: 'index,follow / noindex,nofollow',
  } as ColumnSpec,
  xRobotsTag: {
    key: 'xRobotsTag',
    header: 'X-Robots-Tag 1',
    size: 180,
    kind: 'text',
    info: 'Value of the X-Robots-Tag HTTP response header. Same semantics as meta robots but applied at the server.',
    example: 'noindex, nofollow',
  } as ColumnSpec,
  responseTime: {
    key: 'responseTimeMs',
    header: 'Response Time',
    size: 110,
    kind: 'number',
    info: 'Time-to-first-byte in milliseconds (network + server, excluding parse). Lower is better; >2000 ms is slow.',
    example: '243',
  } as ColumnSpec,
  contentType: {
    key: 'contentType',
    header: 'Content Type',
    size: 170,
    kind: 'text',
    info: 'Raw value of the Content-Type response header (incl. charset).',
    example: 'text/html; charset=utf-8',
  } as ColumnSpec,
  contentLength: {
    key: 'contentLength',
    header: 'Size (Bytes)',
    size: 100,
    kind: 'number',
    info: 'Response body size in bytes (compressed transfer size, post-Content-Encoding).',
    example: '24560',
  } as ColumnSpec,
  depth: {
    key: 'depth',
    header: 'Crawl Depth',
    size: 96,
    kind: 'number',
    info: 'BFS click depth from the start URL. Start URL = 0; its outlinks = 1; etc. High depth often correlates with low importance.',
    example: '3',
  } as ColumnSpec,
  inlinks: {
    key: 'inlinks',
    header: 'Inlinks',
    size: 80,
    kind: 'number',
    info: 'Number of internal pages that link to this URL. A rough internal-PageRank signal.',
    example: '47',
  } as ColumnSpec,
  outlinks: {
    key: 'outlinks',
    header: 'Outlinks',
    size: 84,
    kind: 'number',
    info: 'Number of unique <a> links emitted from this page (internal + external).',
    example: '32',
  } as ColumnSpec,
  linkScore: {
    key: 'linkScore',
    header: 'Link Score',
    size: 92,
    kind: 'number',
    info: 'Internal PageRank, 0–100. Computed over the internal link graph (damping 0.85) and normalised so the most-linked page scores 100. Higher = more internal link equity.',
    example: '73',
  } as ColumnSpec,
  imagesCount: {
    key: 'imagesCount',
    header: 'Images',
    size: 80,
    kind: 'number',
    info: 'Number of <img> elements on the page.',
    example: '12',
  } as ColumnSpec,
  imagesMissingAlt: {
    key: 'imagesMissingAlt',
    header: 'Imgs Missing Alt',
    size: 120,
    kind: 'number',
    info: 'Images on this page that have no alt attribute. WCAG accessibility issue + missed alt-as-anchor SEO opportunity.',
    example: '3',
  } as ColumnSpec,
  redirectTarget: {
    key: 'redirectTarget',
    header: 'Redirect URL',
    size: 360,
    kind: 'mono',
    info: 'Location header value when status is 3xx. The URL the server points to next; chain length is in the URL Details panel.',
    example: 'https://example.com/new-path',
  } as ColumnSpec,
  redirectChainLength: {
    key: 'redirectChainLength',
    header: 'Chain Length',
    size: 96,
    kind: 'number',
    align: 'right',
    info: 'Number of redirect hops from this URL to its terminal target. Filled by the post-crawl `recomputeRedirectChains` walker. >3 trips the "Long Chain" issue.',
    example: '2',
  } as ColumnSpec,
  redirectFinalUrl: {
    key: 'redirectFinalUrl',
    header: 'Final URL',
    size: 360,
    kind: 'mono',
    info: 'Terminal URL the redirect chain resolves to. Empty when this row is itself the terminal (i.e. status is 2xx/4xx/5xx) or when the chain hits a loop.',
    example: 'https://example.com/canonical',
  } as ColumnSpec,
  redirectLoop: {
    key: 'redirectLoop',
    header: 'Loop',
    size: 64,
    kind: 'text',
    info: 'Y when the redirect chain originating at this URL contains a cycle (A → B → A) detected by the cycle-safe walker; the chain is otherwise unwalked.',
    example: 'Y',
  } as ColumnSpec,
  clusterId: {
    key: 'clusterId',
    header: 'Cluster',
    size: 72,
    kind: 'number',
    align: 'right',
    info: 'Near-duplicate cluster ID assigned by the post-crawl SimHash pass. 0 = singleton (no near-duplicates within the configured Hamming threshold). Pages sharing a non-zero cluster ID are mutually similar.',
    example: '0 (no duplicates), 7 (member of cluster #7)',
  } as ColumnSpec,
  clusterSize: {
    key: 'clusterSize',
    header: 'Cluster Size',
    size: 88,
    kind: 'number',
    align: 'right',
    info: 'Number of pages in this URL\'s near-duplicate cluster (1 = no duplicates, ≥2 = part of a duplicate group). Tunable via Settings → Duplicates.',
    example: '1 = unique, 5 = part of a 5-page near-duplicate group',
  } as ColumnSpec,
  contentHash: {
    key: 'contentHash',
    header: 'Content Hash',
    size: 144,
    kind: 'mono',
    info: 'FNV-1a 64-bit hash of the normalised body token stream. Two pages sharing this hash are byte-identical post-tokenisation — the basis of the Exact Duplicate filter.',
    example: '7c3e9f1a8b2d4c5e',
  } as ColumnSpec,
  simhash: {
    key: 'simhash',
    header: 'SimHash',
    size: 144,
    kind: 'mono',
    info: 'Charikar 64-bit SimHash of body shingles. Used by the post-crawl near-duplicate clustering pass. Two SimHashes within the configured Hamming threshold are considered similar.',
    example: '9a4f23bcd1e8077f',
  } as ColumnSpec,
  hsts: {
    key: 'hsts',
    header: 'HSTS',
    size: 220,
    kind: 'mono',
    info: 'Raw `Strict-Transport-Security` header. Empty when missing — for HTTPS pages this is a security regression.',
    example: 'max-age=31536000; includeSubDomains; preload',
  } as ColumnSpec,
  csp: {
    key: 'csp',
    header: 'CSP',
    size: 220,
    kind: 'mono',
    info: 'Raw `Content-Security-Policy` response header. Empty when missing.',
    example: "default-src 'self'; script-src 'self' cdn.example.com",
  } as ColumnSpec,
  xFrameOptions: {
    key: 'xFrameOptions',
    header: 'X-Frame-Options',
    size: 140,
    kind: 'mono',
    info: 'Raw `X-Frame-Options` header. SAMEORIGIN / DENY / ALLOW-FROM. Clickjacking defence.',
    example: 'SAMEORIGIN',
  } as ColumnSpec,
  xContentTypeOptions: {
    key: 'xContentTypeOptions',
    header: 'X-Content-Type-Options',
    size: 160,
    kind: 'mono',
    info: 'Raw `X-Content-Type-Options` header. `nosniff` blocks MIME sniffing — prevents some XSS via content-type confusion.',
    example: 'nosniff',
  } as ColumnSpec,
  mixedContentActive: {
    key: 'mixedContentActive',
    header: 'Mixed Active',
    size: 100,
    kind: 'number',
    align: 'right',
    info: 'HTTP `<script>` / `<link rel=stylesheet>` / `<iframe>` / `<object>` / `<embed>` references on an HTTPS page — browsers BLOCK these silently.',
    example: '0',
  } as ColumnSpec,
  mixedContentPassive: {
    key: 'mixedContentPassive',
    header: 'Mixed Passive',
    size: 100,
    kind: 'number',
    align: 'right',
    info: 'HTTP `<img>` / `<video>` / `<audio>` / `<source>` references on an HTTPS page — rendered but the URL bar reads "Not Secure".',
    example: '0',
  } as ColumnSpec,
  missingSri: {
    key: 'missingSriCount',
    header: 'Missing SRI',
    size: 90,
    kind: 'number',
    align: 'right',
    info: 'Third-party `<script>` / `<link rel=stylesheet>` references without an `integrity=` attribute. SRI is recommended for any cross-origin subresource.',
    example: '0',
  } as ColumnSpec,
  insecureFormAction: {
    key: 'insecureFormActionCount',
    header: 'Insecure Form Action',
    size: 130,
    kind: 'number',
    align: 'right',
    info: 'Number of `<form action="http://…">` declarations on an HTTPS page. Submitting one downgrades the connection.',
    example: '0',
  } as ColumnSpec,
  paginationNext: {
    key: 'paginationNext',
    header: 'rel=next',
    size: 320,
    kind: 'mono',
    info: '`<link rel="next" href="…">` value resolved to absolute. Empty when the page is not paginated forward.',
    example: 'https://example.com/blog/page/2',
  } as ColumnSpec,
  paginationPrev: {
    key: 'paginationPrev',
    header: 'rel=prev',
    size: 320,
    kind: 'mono',
    info: '`<link rel="prev" href="…">` value resolved to absolute. Empty when the page is the first in its pagination cluster.',
    example: 'https://example.com/blog/page/1',
  } as ColumnSpec,
  paginationSequenceBreak: {
    key: 'paginationSequenceBreak',
    header: 'Sequence Break',
    size: 110,
    kind: 'text',
    info: 'Y when this URL belongs to a paginated cluster whose ordinal sequence has a gap (e.g. ?page=1, 2, 4 — page 3 missing). Set by the post-crawl `recomputePaginationSequence` pass.',
    example: 'Y',
  } as ColumnSpec,
  hreflangCount: {
    key: 'hreflangCount',
    header: 'Hreflang Count',
    size: 110,
    kind: 'number',
    align: 'right',
    info: 'Number of `<link rel="alternate" hreflang>` entries declared on this page. 0 = no alternates declared.',
    example: '8',
  } as ColumnSpec,
  hreflangs: {
    key: 'hreflangs',
    header: 'Hreflang Targets',
    size: 360,
    kind: 'mono',
    info: 'JSON-stringified array of `{ lang, href }` pairs. Heavy column — better consumed via the URL Details panel.',
    example: '[{"lang":"en","href":"…"},{"lang":"x-default","href":"…"}]',
  } as ColumnSpec,
  hreflangSelfRefMissing: {
    key: 'hreflangSelfRefMissing',
    header: 'Self-Ref Missing',
    size: 120,
    kind: 'text',
    info: 'Y when the page declares hreflang alternates but no entry whose `href` matches the page URL. Google requires a self-reference.',
    example: 'Y',
  } as ColumnSpec,
  hreflangTargetIssues: {
    key: 'hreflangTargetIssues',
    header: 'Target Issues',
    size: 110,
    kind: 'number',
    align: 'right',
    info: 'Number of hreflang targets that are non-200, noindex, or canonicalised away. Aggregated by the post-crawl pass.',
    example: '0',
  } as ColumnSpec,
  amphtml: {
    key: 'amphtml',
    header: 'AMP HTML',
    size: 360,
    kind: 'mono',
    info: '`<link rel="amphtml" href="…">` value — the AMP version of this page. Empty when the page does not declare an AMP alternate.',
    example: 'https://example.com/amp/post-1',
  } as ColumnSpec,
  schemaTypes: {
    key: 'schemaTypes',
    header: 'Schema Types',
    size: 280,
    kind: 'mono',
    info: 'Comma-joined sorted unique JSON-LD `@type` values declared on the page (Article, BreadcrumbList, Product, …).',
    example: 'Article, BreadcrumbList, Organization',
  } as ColumnSpec,
  schemaBlockCount: {
    key: 'schemaBlockCount',
    header: 'JSON-LD Blocks',
    size: 110,
    kind: 'number',
    align: 'right',
    info: 'Number of `<script type="application/ld+json">` blocks parsed successfully on the page.',
    example: '3',
  } as ColumnSpec,
  schemaInvalidCount: {
    key: 'schemaInvalidCount',
    header: 'Invalid JSON-LD',
    size: 120,
    kind: 'number',
    align: 'right',
    info: 'Number of `<script type="application/ld+json">` blocks that failed to parse as JSON.',
    example: '0',
  } as ColumnSpec,
  schemaDuplicateIds: {
    key: 'schemaDuplicateIds',
    header: 'Duplicate @id',
    size: 110,
    kind: 'number',
    align: 'right',
    info: 'Surplus `@id` occurrences across all JSON-LD blocks (page declares the same `@id` more than once).',
    example: '0',
  } as ColumnSpec,
  metaRefresh: {
    key: 'metaRefresh',
    header: 'Meta Refresh',
    size: 220,
    kind: 'mono',
    info: 'Raw `content` attribute of `<meta http-equiv="refresh">`, e.g. "5; url=/foo".',
    example: '0; url=/new-path',
  } as ColumnSpec,
  metaRefreshUrl: {
    key: 'metaRefreshUrl',
    header: 'Meta Refresh URL',
    size: 320,
    kind: 'mono',
    info: 'Absolute redirect target parsed from the meta-refresh content. Empty when meta-refresh sets only a delay.',
    example: 'https://example.com/new-path',
  } as ColumnSpec,
  extractionResults: {
    key: 'extractionResults',
    header: 'Extracted Data',
    size: 360,
    kind: 'mono',
    info: 'JSON-stringified custom-extraction results map. Heavy column — render verbatim, easier to read in the URL Details panel.',
    example: '{"price":"$19.99","sku":"AB-123"}',
  } as ColumnSpec,
  customSearchHits: {
    key: 'customSearchHits',
    header: 'Custom Search Hits',
    size: 220,
    kind: 'mono',
    info: 'JSON map of `{ term: count }` literal-substring hits from the configured Custom Search terms.',
    example: '{"pricing":3,"beta":1}',
  } as ColumnSpec,
  emptyAnchorCount: {
    key: 'emptyAnchorCount',
    header: 'Empty Anchors',
    size: 110,
    kind: 'number',
    align: 'right',
    info: 'Number of internal `<a>` elements with no usable anchor text or alt — accessibility / SEO regression.',
    example: '0',
  } as ColumnSpec,
  jsOnlyLinksCount: {
    key: 'jsOnlyLinksCount',
    header: 'JS-Only Links',
    size: 110,
    kind: 'number',
    align: 'right',
    info: '`<a>` elements that look clickable but aren\'t crawlable (no href + onclick, `href="javascript:…"`, or `href="#"` with onclick).',
    example: '0',
  } as ColumnSpec,
  canonicalCount: {
    key: 'canonicalCount',
    header: 'Canonical Count',
    size: 110,
    kind: 'number',
    align: 'right',
    info: 'Number of `<link rel="canonical">` tags on the page. >1 is a "Multiple Canonicals" issue.',
    example: '1',
  } as ColumnSpec,
};

export const COLUMN_SPECS: Record<TabKey, ColumnSpec[]> = {
  internal: [
    COL.url,
    COL.contentKind,
    COL.status,
    COL.indexability,
    COL.indexabilityStatus,
    COL.title,
    COL.titleLength,
    COL.metaDescription,
    COL.metaDescriptionLength,
    COL.h1,
    COL.wordCount,
    COL.responseTime,
    COL.contentLength,
    COL.depth,
    COL.inlinks,
    COL.outlinks,
    COL.linkScore,
    COL.imagesCount,
    COL.imagesMissingAlt,
  ],
  external: [
    COL.url,
    COL.contentKind,
    COL.status,
    COL.contentType,
    COL.contentLength,
    COL.responseTime,
    COL.inlinks,
  ],
  'response-codes': [
    COL.url,
    COL.status,
    COL.contentKind,
    COL.redirectTarget,
    COL.indexability,
    COL.responseTime,
    COL.inlinks,
  ],
  url: [COL.url, COL.status, COL.contentKind, COL.indexability, COL.depth, COL.inlinks],
  'page-titles': [
    COL.url,
    COL.title,
    COL.titleLength,
    COL.status,
    COL.indexability,
    COL.inlinks,
  ],
  'meta-description': [
    COL.url,
    COL.metaDescription,
    COL.metaDescriptionLength,
    COL.status,
    COL.indexability,
    COL.inlinks,
  ],
  h1: [
    COL.url,
    COL.h1,
    COL.h1Length,
    COL.h1Count,
    COL.status,
    COL.indexability,
    COL.inlinks,
  ],
  h2: [COL.url, COL.h2Count, COL.status, COL.indexability, COL.inlinks],
  content: [
    COL.url,
    COL.wordCount,
    COL.contentLength,
    COL.clusterId,
    COL.clusterSize,
    COL.status,
    COL.indexability,
    COL.inlinks,
  ],
  // Images / Broken Links / SERP / Visualization tabs have their own
  // layouts (separate components) and don't share the URL-row column
  // schema. Entries kept so Record<TabKey, ...> is total.
  images: [],
  'broken-links': [],
  serp: [],
  pagespeed: [],
  crux: [],
  spelling: [],
  'search-console': [],
  analytics: [],
  ai: [],
  seo: [],
  canonicals: [
    COL.url,
    COL.canonical,
    COL.canonicalCount,
    COL.indexability,
    COL.indexabilityStatus,
    COL.status,
    COL.inlinks,
  ],
  directives: [
    COL.url,
    COL.metaRobots,
    COL.xRobotsTag,
    COL.canonical,
    COL.indexability,
    COL.status,
  ],
  redirects: [
    COL.url,
    COL.status,
    COL.redirectTarget,
    COL.redirectChainLength,
    COL.redirectFinalUrl,
    COL.redirectLoop,
    COL.inlinks,
  ],
  // V1 Faz 3 — new top-level filter tabs. Each starts with the
  // minimum-viable column set; per-tab specialised columns can be
  // added in follow-up sessions without changing the dispatch.
  pagination: [
    COL.url,
    COL.status,
    COL.indexability,
    COL.paginationNext,
    COL.paginationPrev,
    COL.paginationSequenceBreak,
    COL.canonical,
    COL.inlinks,
  ],
  hreflang: [
    COL.url,
    COL.status,
    COL.indexability,
    COL.hreflangCount,
    COL.hreflangSelfRefMissing,
    COL.hreflangTargetIssues,
    COL.hreflangs,
    COL.inlinks,
  ],
  amp: [
    COL.url,
    COL.status,
    COL.indexability,
    COL.amphtml,
    COL.title,
    COL.inlinks,
  ],
  'structured-data': [
    COL.url,
    COL.status,
    COL.indexability,
    COL.schemaTypes,
    COL.schemaBlockCount,
    COL.schemaInvalidCount,
    COL.schemaDuplicateIds,
    COL.inlinks,
  ],
  'meta-refresh': [
    COL.url,
    COL.status,
    COL.indexability,
    COL.metaRefresh,
    COL.metaRefreshUrl,
    COL.inlinks,
  ],
  'custom-extraction': [
    COL.url,
    COL.status,
    COL.indexability,
    COL.extractionResults,
    COL.title,
    COL.inlinks,
  ],
  'custom-search': [
    COL.url,
    COL.status,
    COL.indexability,
    COL.customSearchHits,
    COL.title,
    COL.inlinks,
  ],
  security: [
    COL.url,
    COL.status,
    COL.indexability,
    COL.hsts,
    COL.csp,
    COL.xFrameOptions,
    COL.xContentTypeOptions,
    COL.mixedContentActive,
    COL.mixedContentPassive,
    COL.missingSri,
    COL.insecureFormAction,
  ],
  duplicates: [
    COL.url,
    COL.status,
    COL.indexability,
    COL.title,
    COL.clusterId,
    COL.clusterSize,
    COL.contentHash,
    COL.simhash,
    COL.inlinks,
  ],
  links: [
    COL.url,
    COL.status,
    COL.indexability,
    COL.inlinks,
    COL.outlinks,
    COL.emptyAnchorCount,
    COL.jsOnlyLinksCount,
  ],
};
